# Generated by Django 4.0.3 on 2022-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=15)),
                ('crid', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
