# Generated by Django 4.0.3 on 2022-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_info',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
