# Generated by Django 4.0.3 on 2022-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('event_title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('roll_num', models.IntegerField()),
                ('std_id', models.CharField(max_length=15)),
                ('div', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=10)),
                ('phone_num', models.IntegerField()),
                ('is_present', models.BooleanField(default=False)),
            ],
        ),
    ]
