# Generated by Django 4.0.3 on 2022-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=30)),
                ('presentor', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('learnings', models.TextField()),
                ('pre_req', models.TextField()),
            ],
        ),
    ]
